//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL_UP_01_Gushchin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Reports = new HashSet<Reports>();
        }
    
        public int id { get; set; }
        public System.DateTime datetime_created { get; set; }
        public Nullable<System.DateTime> datetime_closed { get; set; }
        public int id_priority { get; set; }
        public int id_equipment { get; set; }
        public string serial_number_of_equipment { get; set; }
        public int id_type_of_problem { get; set; }
        public string description { get; set; }
        public int id_client { get; set; }
        public int id_worker { get; set; }
        public Nullable<int> id_status { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Priorities Priorities { get; set; }
        public virtual Problems Problems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reports> Reports { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
